[build]
  base = "avi_s_application"
  command = "npm run build"
  publish = ".next"
  # Note: The publish directory is relative to the base directory
  # The full path would be avi_s_application/.next

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = []

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true